server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-service
          uri: lb://USUARIO-SERVICE
          predicates:
            - Path=/api/usuarios/**, /api/clientes/**

        - id: catalogo-service
          uri: lb://CATALOGO-SERVICE
          predicates:
            - Path=/api/productos/**, /api/categorias/**

        - id: inventario-service
          uri: lb://INVENTARIO-SERVICE
          predicates:
            - Path=/api/inventario/**

        - id: carrito-service
          uri: lb://CARRITO-SERVICE
          predicates:
            - Path=/api/carrito/**

        - id: pedido-service
          uri: lb://PEDIDO-SERVICE
          predicates:
            - Path=/api/pedidos/**

        - id: despacho-service
          uri: lb://DESPACHO-SERVICE
          predicates:
            - Path=/api/despachos/**

        - id: pago-service
          uri: lb://PAGO-SERVICE
          predicates:
            - Path=/api/pagos/**

        - id: envios-service
          uri: lb://ENVIOS-SERVICE
          predicates:
            - Path=/api/envios/**

        - id: favoritos-service
          uri: lb://FAVORITOS-SERVICE
          predicates:
            - Path=/api/favoritos/**

        - id: notificaciones-service
          uri: lb://NOTIFICACIONES-SERVICE
          predicates:
            - Path=/api/notificaciones/**

        - id: usuarios-docs
          uri: lb://USUARIO-SERVICE
          predicates:
            - Path=/usuarios-service/v3/api-docs
          filters:
            - RewritePath=/usuarios-service/(?<segment>.*), /${segment}

        - id: catalogo-docs
          uri: lb://CATALOGO-SERVICE
          predicates:
            - Path=/catalogo-service/v3/api-docs
          filters:
            - RewritePath=/catalogo-service/(?<segment>.*), /${segment}

        - id: inventario-docs
          uri: lb://INVENTARIO-SERVICE
          predicates:
            - Path=/inventario-service/v3/api-docs
          filters:
            - RewritePath=/inventario-service/(?<segment>.*), /${segment}

        - id: carrito-docs
          uri: lb://CARRITO-SERVICE
          predicates:
            - Path=/carrito-service/v3/api-docs
          filters:
            - RewritePath=/carrito-service/(?<segment>.*), /${segment}

        - id: pedido-docs
          uri: lb://PEDIDO-SERVICE
          predicates:
            - Path=/pedido-service/v3/api-docs
          filters:
            - RewritePath=/pedido-service/(?<segment>.*), /${segment}

        - id: despacho-docs
          uri: lb://DESPACHO-SERVICE
          predicates:
            - Path=/despacho-service/v3/api-docs
          filters:
            - RewritePath=/despacho-service/(?<segment>.*), /${segment}

        - id: pago-docs
          uri: lb://PAGO-SERVICE
          predicates:
            - Path=/pago-service/v3/api-docs
          filters:
            - RewritePath=/pago-service/(?<segment>.*), /${segment}

        - id: envios-docs
          uri: lb://ENVIOS-SERVICE
          predicates:
            - Path=/envios-service/v3/api-docs
          filters:
            - RewritePath=/envios-service/(?<segment>.*), /${segment}

        - id: favoritos-docs
          uri: lb://FAVORITOS-SERVICE
          predicates:
            - Path=/favoritos-service/v3/api-docs
          filters:
            - RewritePath=/favoritos-service/(?<segment>.*), /${segment}

        - id: notificaciones-docs
          uri: lb://NOTIFICACIONES-SERVICE
          predicates:
            - Path=/notificaciones-service/v3/api-docs
          filters:
            - RewritePath=/notificaciones-service/(?<segment>.*), /${segment}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: usuarios-service
        url: /usuarios-service/v3/api-docs
      - name: catalogo-service
        url: /catalogo-service/v3/api-docs
      - name: inventario-service
        url: /inventario-service/v3/api-docs
      - name: carrito-service
        url: /carrito-service/v3/api-docs
      - name: pedidos-service
        url: /pedido-service/v3/api-docs
      - name: despacho-service
        url: /despacho-service/v3/api-docs
      - name: pagos-service
        url: /pago-service/v3/api-docs
      - name: envios-service
        url: /envios-service/v3/api-docs
      - name: favoritos-service
        url: /favoritos-service/v3/api-docs
      - name: notificaciones-service
        url: /notificaciones-service/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/