server:
  port: 8090

spring:
  application:
    name: notificaciones-service
  datasource:
    url: jdbc:h2:mem:notificacionesdb
    driverClassName: org.h2.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
